# Generated by Django 6.0.3 on 2026-03-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviewsCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
