# Generated by Django 6.0.3 on 2026-03-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_remove_order_id_remove_orderitem_id_order__id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
