# Generated by Django 6.0.3 on 2026-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_order_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
